# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

<% db = URI.parse ENV['DATABASE_URL'] %>
env: &env
  adapter: <%= db.scheme %>
  encoding: unicode
  database: <%= db.path[1..-1] %>
  username: <%= db.user %>
  password: <%= db.password %>

development:
  <<: *env
  pool: 5

test:
  <<: *env
  database: elephant_test
